;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        keyboard-escape-quit
        kill-region
        org-cycle
        org-self-insert-command
        org-shiftright
        smart-open-line
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        ns-copy-including-secondary
        org-beginning-of-line
        sh-assignment
        ))
